<?php
 

 $title = 'Add new category';
 $this->headTitle($title);
 ?>
 <h2 class="page-header"><?php echo $this->escapeHtml($title); ?></h2>
 <?php
 $form->setAttribute('action', $this->url('category', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo '<label>Name: </label>';
 echo $this->formRow($form->get('name'));
 echo '<br><br>';

 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();